{
  "uid" : "22a5f1ac62d8d9c1",
  "name" : "test_get_css_property_footer_email[color-rgba(16, 16, 18, 1)-\\u0446\\u0432\\u0435\\u0442\\u0430 \\u0448\\u0440\\u0438\\u0444\\u0442\\u0430-https://pulsewave.ru/auth/password?email=-chrome]",
  "fullName" : "tests.test_footer.test_footer.TestFooter#test_get_css_property_footer_email",
  "historyId" : "247378015c393ec851b30c09a6210a63",
  "time" : {
    "start" : 1714443558633,
    "stop" : 1714443558633,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome-headless-shell=124.0.6367.60)\nStacktrace:\n#0 0x559ed4130e33 <unknown>\n#1 0x559ed3e20567 <unknown>\n#2 0x559ed3e18879 <unknown>\n#3 0x559ed3e08852 <unknown>\n#4 0x559ed3e09e44 <unknown>\n#5 0x559ed3e08bbe <unknown>\n#6 0x559ed3e082e0 <unknown>\n#7 0x559ed3e08181 <unknown>\n#8 0x559ed3e060ec <unknown>\n#9 0x559ed3e0660a <unknown>\n#10 0x559ed3e22eef <unknown>\n#11 0x559ed3eac695 <unknown>\n#12 0x559ed3e8d362 <unknown>\n#13 0x559ed3eabae2 <unknown>\n#14 0x559ed3e8d103 <unknown>\n#15 0x559ed3e5e1ba <unknown>\n#16 0x559ed3e5eb8e <unknown>\n#17 0x559ed40f559b <unknown>\n#18 0x559ed40f934b <unknown>\n#19 0x559ed40e1681 <unknown>\n#20 0x559ed40f9eb2 <unknown>\n#21 0x559ed40c66af <unknown>\n#22 0x559ed4120428 <unknown>\n#23 0x559ed4120600 <unknown>\n#24 0x559ed412ff84 <unknown>\n#25 0x7f42a6e94ac3 <unknown>",
  "statusTrace" : "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"24132af40705224134fa0ec653e3e1ae\")>\nurl = 'https://pulsewave.ru/auth/password?email='\n\n    @pytest.fixture()\n    def footer_open(driver, url):\n        page = FooterPage(driver)\n>       driver.get(url)\n\ntests/test_footer/conftest.py:8: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:356: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:347: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f17c7d81c70>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#23 0x559ed4120600 \\\\u003Cunknown>\\\\n#24 0x559ed412ff84 \\\\u003Cunknown>\\\\n#25 0x7f42a6e94ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome-headless-shell=124.0.6367.60)\nE       Stacktrace:\nE       #0 0x559ed4130e33 <unknown>\nE       #1 0x559ed3e20567 <unknown>\nE       #2 0x559ed3e18879 <unknown>\nE       #3 0x559ed3e08852 <unknown>\nE       #4 0x559ed3e09e44 <unknown>\nE       #5 0x559ed3e08bbe <unknown>\nE       #6 0x559ed3e082e0 <unknown>\nE       #7 0x559ed3e08181 <unknown>\nE       #8 0x559ed3e060ec <unknown>\nE       #9 0x559ed3e0660a <unknown>\nE       #10 0x559ed3e22eef <unknown>\nE       #11 0x559ed3eac695 <unknown>\nE       #12 0x559ed3e8d362 <unknown>\nE       #13 0x559ed3eabae2 <unknown>\nE       #14 0x559ed3e8d103 <unknown>\nE       #15 0x559ed3e5e1ba <unknown>\nE       #16 0x559ed3e5eb8e <unknown>\nE       #17 0x559ed40f559b <unknown>\nE       #18 0x559ed40f934b <unknown>\nE       #19 0x559ed40e1681 <unknown>\nE       #20 0x559ed40f9eb2 <unknown>\nE       #21 0x559ed40c66af <unknown>\nE       #22 0x559ed4120428 <unknown>\nE       #23 0x559ed4120600 <unknown>\nE       #24 0x559ed412ff84 <unknown>\nE       #25 0x7f42a6e94ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:229: WebDriverException",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "footer_open",
    "time" : {
      "start" : 1714443558833,
      "stop" : 1714443559052,
      "duration" : 219
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome-headless-shell=124.0.6367.60)\nStacktrace:\n#0 0x559ed4130e33 <unknown>\n#1 0x559ed3e20567 <unknown>\n#2 0x559ed3e18879 <unknown>\n#3 0x559ed3e08852 <unknown>\n#4 0x559ed3e09e44 <unknown>\n#5 0x559ed3e08bbe <unknown>\n#6 0x559ed3e082e0 <unknown>\n#7 0x559ed3e08181 <unknown>\n#8 0x559ed3e060ec <unknown>\n#9 0x559ed3e0660a <unknown>\n#10 0x559ed3e22eef <unknown>\n#11 0x559ed3eac695 <unknown>\n#12 0x559ed3e8d362 <unknown>\n#13 0x559ed3eabae2 <unknown>\n#14 0x559ed3e8d103 <unknown>\n#15 0x559ed3e5e1ba <unknown>\n#16 0x559ed3e5eb8e <unknown>\n#17 0x559ed40f559b <unknown>\n#18 0x559ed40f934b <unknown>\n#19 0x559ed40e1681 <unknown>\n#20 0x559ed40f9eb2 <unknown>\n#21 0x559ed40c66af <unknown>\n#22 0x559ed4120428 <unknown>\n#23 0x559ed4120600 <unknown>\n#24 0x559ed412ff84 <unknown>\n#25 0x7f42a6e94ac3 <unknown>\n\n",
    "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 917, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/PulseWave/PulseWave/tests/test_footer/conftest.py\", line 8, in footer_open\n    driver.get(url)\n  File \"/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 356, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  }, {
    "name" : "clear_allure_results_folder",
    "time" : {
      "start" : 1714443483373,
      "stop" : 1714443483373,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "_session_faker",
    "time" : {
      "start" : 1714443483355,
      "stop" : 1714443483372,
      "duration" : 17
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "driver",
    "time" : {
      "start" : 1714443558634,
      "stop" : 1714443558832,
      "duration" : 198
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "afterStages" : [ {
    "name" : "driver::0",
    "time" : {
      "start" : 1714443559084,
      "stop" : 1714443559142,
      "duration" : 58
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "epic",
    "value" : "Тестирование Футера"
  }, {
    "name" : "tag",
    "value" : "regress"
  }, {
    "name" : "parentSuite",
    "value" : "tests.test_footer"
  }, {
    "name" : "suite",
    "value" : "test_footer"
  }, {
    "name" : "subSuite",
    "value" : "TestFooter"
  }, {
    "name" : "host",
    "value" : "fv-az1385-609"
  }, {
    "name" : "thread",
    "value" : "2312-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.test_footer.test_footer"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "browser",
    "value" : "'chrome'"
  }, {
    "name" : "css_property",
    "value" : "'color'"
  }, {
    "name" : "figma",
    "value" : "'rgba(16, 16, 18, 1)'"
  }, {
    "name" : "name",
    "value" : "'цвета шрифта'"
  }, {
    "name" : "url",
    "value" : "'https://pulsewave.ru/auth/password?email='"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 3,
        "skipped" : 0,
        "passed" : 11,
        "unknown" : 0,
        "total" : 14
      },
      "items" : [ {
        "uid" : "cbd5b815348277c",
        "reportUrl" : "https://Nat754.github.io/PulseWave/9//#testresult/cbd5b815348277c",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome-headless-shell=124.0.6367.60)\nStacktrace:\n#0 0x55691f35fe33 <unknown>\n#1 0x55691f04f567 <unknown>\n#2 0x55691f047879 <unknown>\n#3 0x55691f037852 <unknown>\n#4 0x55691f038e44 <unknown>\n#5 0x55691f037bbe <unknown>\n#6 0x55691f0372e0 <unknown>\n#7 0x55691f037181 <unknown>\n#8 0x55691f0350ec <unknown>\n#9 0x55691f03560a <unknown>\n#10 0x55691f051eef <unknown>\n#11 0x55691f0db695 <unknown>\n#12 0x55691f0bc362 <unknown>\n#13 0x55691f0daae2 <unknown>\n#14 0x55691f0bc103 <unknown>\n#15 0x55691f08d1ba <unknown>\n#16 0x55691f08db8e <unknown>\n#17 0x55691f32459b <unknown>\n#18 0x55691f32834b <unknown>\n#19 0x55691f310681 <unknown>\n#20 0x55691f328eb2 <unknown>\n#21 0x55691f2f56af <unknown>\n#22 0x55691f34f428 <unknown>\n#23 0x55691f34f600 <unknown>\n#24 0x55691f35ef84 <unknown>\n#25 0x7f83d2294ac3 <unknown>",
        "time" : {
          "start" : 1714357217179,
          "stop" : 1714357217179,
          "duration" : 0
        }
      }, {
        "uid" : "3419088730c0bf28",
        "reportUrl" : "https://Nat754.github.io/PulseWave/8//#testresult/3419088730c0bf28",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x5599ce951e33 <unknown>\n#1 0x5599ce641567 <unknown>\n#2 0x5599ce68c27d <unknown>\n#3 0x5599ce68c331 <unknown>\n#4 0x5599ce6cf624 <unknown>\n#5 0x5599ce6ae38d <unknown>\n#6 0x5599ce6ccae2 <unknown>\n#7 0x5599ce6ae103 <unknown>\n#8 0x5599ce67f1ba <unknown>\n#9 0x5599ce67fb8e <unknown>\n#10 0x5599ce91659b <unknown>\n#11 0x5599ce91a34b <unknown>\n#12 0x5599ce902681 <unknown>\n#13 0x5599ce91aeb2 <unknown>\n#14 0x5599ce8e76af <unknown>\n#15 0x5599ce941428 <unknown>\n#16 0x5599ce941600 <unknown>\n#17 0x5599ce950f84 <unknown>\n#18 0x7fbcdba94ac3 <unknown>",
        "time" : {
          "start" : 1714271729602,
          "stop" : 1714271729602,
          "duration" : 0
        }
      }, {
        "uid" : "b53e576e7c1c594d",
        "reportUrl" : "https://Nat754.github.io/PulseWave/7//#testresult/b53e576e7c1c594d",
        "status" : "passed",
        "time" : {
          "start" : 1714184819994,
          "stop" : 1714184820029,
          "duration" : 35
        }
      }, {
        "uid" : "d337faf90fe57088",
        "reportUrl" : "https://Nat754.github.io/PulseWave/6//#testresult/d337faf90fe57088",
        "status" : "passed",
        "time" : {
          "start" : 1714148318798,
          "stop" : 1714148318833,
          "duration" : 35
        }
      }, {
        "uid" : "4c766d926237b5f4",
        "reportUrl" : "https://Nat754.github.io/PulseWave/6//#testresult/4c766d926237b5f4",
        "status" : "passed",
        "time" : {
          "start" : 1714098366440,
          "stop" : 1714098366475,
          "duration" : 35
        }
      }, {
        "uid" : "74ec0e0d5cdb7804",
        "reportUrl" : "https://Nat754.github.io/PulseWave/5//#testresult/74ec0e0d5cdb7804",
        "status" : "passed",
        "time" : {
          "start" : 1714014269407,
          "stop" : 1714014269441,
          "duration" : 34
        }
      }, {
        "uid" : "95fb12e85d0cb00a",
        "reportUrl" : "https://Nat754.github.io/PulseWave/211//#testresult/95fb12e85d0cb00a",
        "status" : "passed",
        "time" : {
          "start" : 1713945755213,
          "stop" : 1713945755247,
          "duration" : 34
        }
      }, {
        "uid" : "c9ed39d1890d0b28",
        "reportUrl" : "https://Nat754.github.io/PulseWave/4//#testresult/c9ed39d1890d0b28",
        "status" : "passed",
        "time" : {
          "start" : 1713925549120,
          "stop" : 1713925549153,
          "duration" : 33
        }
      }, {
        "uid" : "e054f750c2315c46",
        "reportUrl" : "https://Nat754.github.io/PulseWave/211//#testresult/e054f750c2315c46",
        "status" : "passed",
        "time" : {
          "start" : 1713901385911,
          "stop" : 1713901385945,
          "duration" : 34
        }
      }, {
        "uid" : "ea1448f316633245",
        "reportUrl" : "https://Nat754.github.io/PulseWave/210//#testresult/ea1448f316633245",
        "status" : "passed",
        "time" : {
          "start" : 1713885553209,
          "stop" : 1713885553244,
          "duration" : 35
        }
      }, {
        "uid" : "4f22cc02b5e67c87",
        "reportUrl" : "https://Nat754.github.io/PulseWave/209//#testresult/4f22cc02b5e67c87",
        "status" : "passed",
        "time" : {
          "start" : 1713883460544,
          "stop" : 1713883460578,
          "duration" : 34
        }
      }, {
        "uid" : "ec28b0aed9beb101",
        "reportUrl" : "https://Nat754.github.io/PulseWave/209//#testresult/ec28b0aed9beb101",
        "status" : "passed",
        "time" : {
          "start" : 1713881967735,
          "stop" : 1713881967770,
          "duration" : 35
        }
      }, {
        "uid" : "265d3a191032baf",
        "reportUrl" : "https://Nat754.github.io/PulseWave/208//#testresult/265d3a191032baf",
        "status" : "passed",
        "time" : {
          "start" : 1713879143669,
          "stop" : 1713879143703,
          "duration" : 34
        }
      } ]
    },
    "tags" : [ "regress" ]
  },
  "source" : "22a5f1ac62d8d9c1.json",
  "parameterValues" : [ "'chrome'", "'color'", "'rgba(16, 16, 18, 1)'", "'цвета шрифта'", "'https://pulsewave.ru/auth/password?email='" ]
}