{
  "uid" : "f14d64ebefcd20a5",
  "name" : "Проверка что авторизованный пользователь может выйти из аккаунта",
  "fullName" : "tests.test_workspace_page.test_workspace_page.TestWorkspacePage#test_auth_user_logout",
  "historyId" : "ef004c13c91f13fae735f1a09c2da0ef",
  "time" : {
    "start" : 1714357275584,
    "stop" : 1714357275584,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome-headless-shell=124.0.6367.60)\nStacktrace:\n#0 0x56544449be33 <unknown>\n#1 0x56544418b567 <unknown>\n#2 0x565444183879 <unknown>\n#3 0x565444173852 <unknown>\n#4 0x565444174e44 <unknown>\n#5 0x565444173bbe <unknown>\n#6 0x5654441732e0 <unknown>\n#7 0x565444173181 <unknown>\n#8 0x5654441710ec <unknown>\n#9 0x56544417160a <unknown>\n#10 0x56544418deef <unknown>\n#11 0x565444217695 <unknown>\n#12 0x5654441f8362 <unknown>\n#13 0x565444216ae2 <unknown>\n#14 0x5654441f8103 <unknown>\n#15 0x5654441c91ba <unknown>\n#16 0x5654441c9b8e <unknown>\n#17 0x56544446059b <unknown>\n#18 0x56544446434b <unknown>\n#19 0x56544444c681 <unknown>\n#20 0x565444464eb2 <unknown>\n#21 0x5654444316af <unknown>\n#22 0x56544448b428 <unknown>\n#23 0x56544448b600 <unknown>\n#24 0x56544449af84 <unknown>\n#25 0x7fac12294ac3 <unknown>",
  "statusTrace" : "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"65a74c5ab8015bc914817e9214c91fda\")>\n\n    @pytest.fixture(scope='function')\n    def auth_user(driver):\n        page_auth_user = LoginPage(driver)\n>       driver.get(Constant.LOGIN_PAGE)\n\ntests/conftest.py:10: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:356: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:347: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f7971c69040>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#23 0x56544448b600 \\\\u003Cunknown>\\\\n#24 0x56544449af84 \\\\u003Cunknown>\\\\n#25 0x7fac12294ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome-headless-shell=124.0.6367.60)\nE       Stacktrace:\nE       #0 0x56544449be33 <unknown>\nE       #1 0x56544418b567 <unknown>\nE       #2 0x565444183879 <unknown>\nE       #3 0x565444173852 <unknown>\nE       #4 0x565444174e44 <unknown>\nE       #5 0x565444173bbe <unknown>\nE       #6 0x5654441732e0 <unknown>\nE       #7 0x565444173181 <unknown>\nE       #8 0x5654441710ec <unknown>\nE       #9 0x56544417160a <unknown>\nE       #10 0x56544418deef <unknown>\nE       #11 0x565444217695 <unknown>\nE       #12 0x5654441f8362 <unknown>\nE       #13 0x565444216ae2 <unknown>\nE       #14 0x5654441f8103 <unknown>\nE       #15 0x5654441c91ba <unknown>\nE       #16 0x5654441c9b8e <unknown>\nE       #17 0x56544446059b <unknown>\nE       #18 0x56544446434b <unknown>\nE       #19 0x56544444c681 <unknown>\nE       #20 0x565444464eb2 <unknown>\nE       #21 0x5654444316af <unknown>\nE       #22 0x56544448b428 <unknown>\nE       #23 0x56544448b600 <unknown>\nE       #24 0x56544449af84 <unknown>\nE       #25 0x7fac12294ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:229: WebDriverException",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "auth_user",
    "time" : {
      "start" : 1714357275783,
      "stop" : 1714357275937,
      "duration" : 154
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome-headless-shell=124.0.6367.60)\nStacktrace:\n#0 0x56544449be33 <unknown>\n#1 0x56544418b567 <unknown>\n#2 0x565444183879 <unknown>\n#3 0x565444173852 <unknown>\n#4 0x565444174e44 <unknown>\n#5 0x565444173bbe <unknown>\n#6 0x5654441732e0 <unknown>\n#7 0x565444173181 <unknown>\n#8 0x5654441710ec <unknown>\n#9 0x56544417160a <unknown>\n#10 0x56544418deef <unknown>\n#11 0x565444217695 <unknown>\n#12 0x5654441f8362 <unknown>\n#13 0x565444216ae2 <unknown>\n#14 0x5654441f8103 <unknown>\n#15 0x5654441c91ba <unknown>\n#16 0x5654441c9b8e <unknown>\n#17 0x56544446059b <unknown>\n#18 0x56544446434b <unknown>\n#19 0x56544444c681 <unknown>\n#20 0x565444464eb2 <unknown>\n#21 0x5654444316af <unknown>\n#22 0x56544448b428 <unknown>\n#23 0x56544448b600 <unknown>\n#24 0x56544449af84 <unknown>\n#25 0x7fac12294ac3 <unknown>\n\n",
    "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 917, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/PulseWave/PulseWave/tests/conftest.py\", line 10, in auth_user\n    driver.get(Constant.LOGIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 356, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  }, {
    "name" : "clear_allure_results_folder",
    "time" : {
      "start" : 1714357159972,
      "stop" : 1714357159973,
      "duration" : 1
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "driver",
    "time" : {
      "start" : 1714357275585,
      "stop" : 1714357275782,
      "duration" : 197
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "_session_faker",
    "time" : {
      "start" : 1714357159955,
      "stop" : 1714357159972,
      "duration" : 17
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "afterStages" : [ {
    "name" : "driver::0",
    "time" : {
      "start" : 1714357275971,
      "stop" : 1714357276029,
      "duration" : 58
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "epic",
    "value" : "Тестирование страницы 'Рабочие пространства'"
  }, {
    "name" : "tag",
    "value" : "regress"
  }, {
    "name" : "parentSuite",
    "value" : "tests.test_workspace_page"
  }, {
    "name" : "suite",
    "value" : "test_workspace_page"
  }, {
    "name" : "subSuite",
    "value" : "TestWorkspacePage"
  }, {
    "name" : "host",
    "value" : "fv-az842-111"
  }, {
    "name" : "thread",
    "value" : "2300-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.test_workspace_page.test_workspace_page"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "browser",
    "value" : "'chrome'"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 6,
        "skipped" : 0,
        "passed" : 7,
        "unknown" : 0,
        "total" : 13
      },
      "items" : [ {
        "uid" : "fcbf865b86a58b93",
        "reportUrl" : "https://Nat754.github.io/PulseWave/8//#testresult/fcbf865b86a58b93",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x555fd4c75e33 <unknown>\n#1 0x555fd4965567 <unknown>\n#2 0x555fd49b027d <unknown>\n#3 0x555fd49b0331 <unknown>\n#4 0x555fd49f3624 <unknown>\n#5 0x555fd49d238d <unknown>\n#6 0x555fd49f0ae2 <unknown>\n#7 0x555fd49d2103 <unknown>\n#8 0x555fd49a31ba <unknown>\n#9 0x555fd49a3b8e <unknown>\n#10 0x555fd4c3a59b <unknown>\n#11 0x555fd4c3e34b <unknown>\n#12 0x555fd4c26681 <unknown>\n#13 0x555fd4c3eeb2 <unknown>\n#14 0x555fd4c0b6af <unknown>\n#15 0x555fd4c65428 <unknown>\n#16 0x555fd4c65600 <unknown>\n#17 0x555fd4c74f84 <unknown>\n#18 0x7ff97ec94ac3 <unknown>",
        "time" : {
          "start" : 1714274504572,
          "stop" : 1714274504572,
          "duration" : 0
        }
      }, {
        "uid" : "9338b577649bb89c",
        "reportUrl" : "https://Nat754.github.io/PulseWave/7//#testresult/9338b577649bb89c",
        "status" : "passed",
        "time" : {
          "start" : 1714185433211,
          "stop" : 1714185433653,
          "duration" : 442
        }
      }, {
        "uid" : "d35241152fd6a04e",
        "reportUrl" : "https://Nat754.github.io/PulseWave/6//#testresult/d35241152fd6a04e",
        "status" : "passed",
        "time" : {
          "start" : 1714148841601,
          "stop" : 1714148842006,
          "duration" : 405
        }
      }, {
        "uid" : "bca65d9f6d56e9c1",
        "reportUrl" : "https://Nat754.github.io/PulseWave/6//#testresult/bca65d9f6d56e9c1",
        "status" : "passed",
        "time" : {
          "start" : 1714098891953,
          "stop" : 1714098892424,
          "duration" : 471
        }
      }, {
        "uid" : "73c02acb45438e81",
        "reportUrl" : "https://Nat754.github.io/PulseWave/5//#testresult/73c02acb45438e81",
        "status" : "passed",
        "time" : {
          "start" : 1714014731495,
          "stop" : 1714014731921,
          "duration" : 426
        }
      }, {
        "uid" : "bdad2f710fa03fce",
        "reportUrl" : "https://Nat754.github.io/PulseWave/211//#testresult/bdad2f710fa03fce",
        "status" : "passed",
        "time" : {
          "start" : 1713946244234,
          "stop" : 1713946244754,
          "duration" : 520
        }
      }, {
        "uid" : "2d0d37ce2961bc3f",
        "reportUrl" : "https://Nat754.github.io/PulseWave/4//#testresult/2d0d37ce2961bc3f",
        "status" : "passed",
        "time" : {
          "start" : 1713926036432,
          "stop" : 1713926036936,
          "duration" : 504
        }
      }, {
        "uid" : "7191c6273a9d3db7",
        "reportUrl" : "https://Nat754.github.io/PulseWave/211//#testresult/7191c6273a9d3db7",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame\n  (Session info: chrome-headless-shell=123.0.6312.122); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception\nStacktrace:\n#0 0x557166a73863 <unknown>\n#1 0x5571667698c6 <unknown>\n#2 0x55716676ee75 <unknown>\n#3 0x557166770bce <unknown>\n#4 0x557166770c5c <unknown>\n#5 0x5571667b61c2 <unknown>\n#6 0x5571667b53da <unknown>\n#7 0x5571667a9507 <unknown>\n#8 0x5571667d65a2 <unknown>\n#9 0x5571667a8e98 <unknown>\n#10 0x5571667d676e <unknown>\n#11 0x5571667f4c19 <unknown>\n#12 0x5571667d6343 <unknown>\n#13 0x5571667a7593 <unknown>\n#14 0x5571667a7f5e <unknown>\n#15 0x557166a3784b <unknown>\n#16 0x557166a3b7a5 <unknown>\n#17 0x557166a25571 <unknown>\n#18 0x557166a3c332 <unknown>\n#19 0x557166a0a87f <unknown>\n#20 0x557166a62728 <unknown>\n#21 0x557166a628fb <unknown>\n#22 0x557166a729b4 <unknown>\n#23 0x7ff7a7694ac3 <unknown>",
        "time" : {
          "start" : 1713901922036,
          "stop" : 1713901922343,
          "duration" : 307
        }
      }, {
        "uid" : "8c0d4190ee64de5e",
        "reportUrl" : "https://Nat754.github.io/PulseWave/210//#testresult/8c0d4190ee64de5e",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame\n  (Session info: chrome-headless-shell=123.0.6312.122); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception\nStacktrace:\n#0 0x555a1c031863 <unknown>\n#1 0x555a1bd278c6 <unknown>\n#2 0x555a1bd2ce75 <unknown>\n#3 0x555a1bd2ee88 <unknown>\n#4 0x555a1bdb3c17 <unknown>\n#5 0x555a1bd945a2 <unknown>\n#6 0x555a1bdb2c19 <unknown>\n#7 0x555a1bd94343 <unknown>\n#8 0x555a1bd65593 <unknown>\n#9 0x555a1bd65f5e <unknown>\n#10 0x555a1bff584b <unknown>\n#11 0x555a1bff97a5 <unknown>\n#12 0x555a1bfe3571 <unknown>\n#13 0x555a1bffa332 <unknown>\n#14 0x555a1bfc887f <unknown>\n#15 0x555a1c020728 <unknown>\n#16 0x555a1c0208fb <unknown>\n#17 0x555a1c0309b4 <unknown>\n#18 0x7f6373894ac3 <unknown>",
        "time" : {
          "start" : 1713886175357,
          "stop" : 1713886175651,
          "duration" : 294
        }
      }, {
        "uid" : "44cfc36f9c11fa28",
        "reportUrl" : "https://Nat754.github.io/PulseWave/209//#testresult/44cfc36f9c11fa28",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame\n  (Session info: chrome-headless-shell=123.0.6312.122); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception\nStacktrace:\n#0 0x55eeaa777863 <unknown>\n#1 0x55eeaa46d8c6 <unknown>\n#2 0x55eeaa472e75 <unknown>\n#3 0x55eeaa474e88 <unknown>\n#4 0x55eeaa4f9c17 <unknown>\n#5 0x55eeaa4da5a2 <unknown>\n#6 0x55eeaa4f8c19 <unknown>\n#7 0x55eeaa4da343 <unknown>\n#8 0x55eeaa4ab593 <unknown>\n#9 0x55eeaa4abf5e <unknown>\n#10 0x55eeaa73b84b <unknown>\n#11 0x55eeaa73f7a5 <unknown>\n#12 0x55eeaa729571 <unknown>\n#13 0x55eeaa740332 <unknown>\n#14 0x55eeaa70e87f <unknown>\n#15 0x55eeaa766728 <unknown>\n#16 0x55eeaa7668fb <unknown>\n#17 0x55eeaa7769b4 <unknown>\n#18 0x7fe396294ac3 <unknown>",
        "time" : {
          "start" : 1713884059372,
          "stop" : 1713884059664,
          "duration" : 292
        }
      }, {
        "uid" : "5d6857b5d5264b2e",
        "reportUrl" : "https://Nat754.github.io/PulseWave/209//#testresult/5d6857b5d5264b2e",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame\n  (Session info: chrome-headless-shell=123.0.6312.122); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception\nStacktrace:\n#0 0x5598d1bde863 <unknown>\n#1 0x5598d18d48c6 <unknown>\n#2 0x5598d18d9e75 <unknown>\n#3 0x5598d18dbbce <unknown>\n#4 0x5598d18dbc5c <unknown>\n#5 0x5598d19211c2 <unknown>\n#6 0x5598d19143a1 <unknown>\n#7 0x5598d19415a2 <unknown>\n#8 0x5598d1913e98 <unknown>\n#9 0x5598d194176e <unknown>\n#10 0x5598d195fc19 <unknown>\n#11 0x5598d1941343 <unknown>\n#12 0x5598d1912593 <unknown>\n#13 0x5598d1912f5e <unknown>\n#14 0x5598d1ba284b <unknown>\n#15 0x5598d1ba67a5 <unknown>\n#16 0x5598d1b90571 <unknown>\n#17 0x5598d1ba7332 <unknown>\n#18 0x5598d1b7587f <unknown>\n#19 0x5598d1bcd728 <unknown>\n#20 0x5598d1bcd8fb <unknown>\n#21 0x5598d1bdd9b4 <unknown>\n#22 0x7fcc67894ac3 <unknown>",
        "time" : {
          "start" : 1713882593647,
          "stop" : 1713882593955,
          "duration" : 308
        }
      }, {
        "uid" : "fd106e7038ddf492",
        "reportUrl" : "https://Nat754.github.io/PulseWave/208//#testresult/fd106e7038ddf492",
        "status" : "passed",
        "time" : {
          "start" : 1713879771347,
          "stop" : 1713879771758,
          "duration" : 411
        }
      } ]
    },
    "tags" : [ "regress" ]
  },
  "source" : "f14d64ebefcd20a5.json",
  "parameterValues" : [ "'chrome'" ]
}